# código com a interface da IHM, criado com o software Page (arraste e solte)

#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 01, 2025

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

from gui import pwm_suporte

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'

class Toplevel1:
    def __init__(self, top=None):
        top.geometry("800x500+852+223")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Controle PWM ESP32")
        top.configure(background="#d9d9d9")

        self.top = top

        self.LabelSetpoint = tk.Label(self.top, text="Setpoint (V):", background="#d9d9d9")
        self.LabelSetpoint.place(relx=0.017, rely=0.05)
        self.EntrySetpoint = tk.Entry(self.top)
        self.EntrySetpoint.place(relx=0.2, rely=0.05, height=20, relwidth=0.14)

        self.LabelKp = tk.Label(self.top, text="Kp:", background="#d9d9d9")
        self.LabelKp.place(relx=0.017, rely=0.10)
        self.EntryKp = tk.Entry(self.top)
        self.EntryKp.place(relx=0.2, rely=0.10, height=20, relwidth=0.14)

        self.LabelKi = tk.Label(self.top, text="Ki:", background="#d9d9d9")
        self.LabelKi.place(relx=0.017, rely=0.15)
        self.EntryKi = tk.Entry(self.top)
        self.EntryKi.place(relx=0.2, rely=0.15, height=20, relwidth=0.14)

        self.LabelKd = tk.Label(self.top, text="Kd:", background="#d9d9d9")
        self.LabelKd.place(relx=0.017, rely=0.20)
        self.EntryKd = tk.Entry(self.top)
        self.EntryKd.place(relx=0.2, rely=0.20, height=20, relwidth=0.14)

        self.ButtonMalhaAberta = tk.Button(self.top, text="Malha Aberta", command=self.ativar_malha_aberta)
        self.ButtonMalhaAberta.place(relx=0.02, rely=0.28, height=30, width=100)

        self.ButtonMalhaFechada = tk.Button(self.top, text="Malha Fechada", command=self.ativar_malha_fechada)
        self.ButtonMalhaFechada.place(relx=0.14, rely=0.28, height=30, width=110)

        self.LabelPWM = tk.Label(self.top)
        self.LabelPWM.place(relx=0.017, rely=0.35, height=31, width=104)
        self.LabelPWM.configure(background="#d9d9d9")
        self.LabelPWM.configure(foreground="#000000")
        self.LabelPWM.configure(text="PWM Manual:")

        self.EntryPWM = tk.Entry(self.top)
        self.EntryPWM.place(relx=0.2, rely=0.35, height=20, relwidth=0.14)
        self.EntryPWM.configure(background="white")
        self.EntryPWM.configure(foreground="#000000")

        self.ButtonEnviarTodos = tk.Button(
            self.top,
            text="Enviar",
            command=self.enviar_todos
        )
        self.ButtonEnviarTodos.place(relx=0.233, rely=0.40, height=26, width=60)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.35, rely=0.011, relheight=0.95, relwidth=0.625)
        self.Frame1.configure(relief='groove', borderwidth="2", background="#d9d9d9")

        pwm_suporte.iniciar_grafico(
            self.Frame1,
            self.EntrySetpoint,
            self.EntryKp,
            self.EntryKi,
            self.EntryKd,
            self.ButtonMalhaAberta,
            self.ButtonMalhaFechada,
            self.EntryPWM
        )

    def enviar_todos(self):
        pwm_suporte.enviar_todos(
            self.EntryPWM.get(),
            self.EntrySetpoint.get(),
            self.EntryKp.get(),
            self.EntryKi.get(),
            self.EntryKd.get()
        )

    def ativar_malha_aberta(self):
        pwm_suporte.ativar_malha_aberta()

    def ativar_malha_fechada(self):
        pwm_suporte.ativar_malha_fechada()

def start_up():
    pwm_suporte.main()

if __name__ == '__main__':
    pwm_suporte.main()
